services:
  web:
    # build: .
    image: akatgelar/citiasia-tanahbumbu-superapps:latest
    container_name: 'tanahbumbu-superapps'
    env_file:
      - .env
    ports:
      - "2011:80"
    #volumes:
    #  - /home/ekosistemdesa/app/tanahbumbu-superapps/storage:/var/www/public/storage
    restart: always
